### ISSUE TITLE
Proto style/conventions

### ISSUE THREAD

**Issue by future-highway** [aurae-runtime/api#4]
I think we should generally try to follow the [style guide](https://developers.google.com/protocol-buffers/docs/style) in the proto files. (I think the conventions regarding casing are the most important, given many language generators means a possible reliance on specific casing conventions to generate idiomatic code).

It is short, but main points:

- Files should be named `lower_snake_case.proto`
- Files should be ordered in the following manner
```proto
// AURAE LICENSE HEADER

syntax = "proto3";

package lower_snake_case_package_name;

// imports sorted alphabetically
import "path/to/dependency.proto";
import "path/to/other.proto";

// file options

// everything else

``` 
- Services should be named `UpperCamelCase` (aka PascalCase)
- Service methods should be named `UpperCamelCase`
- Messages should be named `UpperCamelCase`
- Field names, including `oneof` and extension names, should be `snake_case`
- `repeated` fields should have pluralized names
- Enums should be named `UpperCamelCase`
- Enum variants should be `SCREAMING_SNAKE_CASE` 
- (Suggested) Enums should NOT be nested, and their variants should be prefixed with the enum's name
```proto
enum FooBar {
  FOO_BAR_UNSPECIFIED = 0;
  FOO_BAR_FIRST_VALUE = 1;
  FOO_BAR_SECOND_VALUE = 2;
}
``` 
- (Suggested) The zero value enum variants should have the suffix `UNSPECIFIED`

---

Another convention that I've stuck to but can't remember where it is documented (so definitely a suggestion, but is meant to reduce the likelihood of future breaking changes):

- rpc methods (e.g., `MyMethod`) should have dedicated request and response messages named `MyMethodRequest` and `MyMethodResponse` (It is the convention I have found the most annoying, but it will likely be useful for macro code generation in rust too)

**Comment by krisnova** [comment]
Can we please add this to the documentation instead of an issue? Just open up a pull request to this repository with a `.md` file wherever you feel like it would be best fit.
